In [ ]:
#@title Copyright 2020 Google LLC. Double-click here for license information.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NumPy UltraQuick Tutorial

NumPy adalah Python library untuk membuat dan memanipulasi vector dan matriks. Notebook ini tidak berisikan semua tutorial cara menggunakan NumPy, hanya memberikan tutorial yang cukup untuk menggunakan NumPy sebagai pemula.

## Import NumPy modul

In [2]:
import numpy as np

## Membuat array

Gunakan kode `np.array` untuk membuat matriks NumPy dengan nilai yang sudah kamu tentukan. Sebagai contoh panggil `np.array` untuk membuat vector 8-elemen

In [3]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


kamu juga bisa menggunakan `np.array` untuk membuat matriks 2 dimensi. Untuk membuat matriks 2 dimensi, tandai dimensi tambahan menggunakan `[]`. Sebagai contoh kode dibawah untuk membuat matriks 3x2

In [4]:
two_dimensional_array = np.array([[6,5], [11,7], [4,8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


Untuk membuat matriks yang isinya semuanya 0, gunakan kode `np.zeros(shape, dtype)`. Untuk membuat matriks yang isinya semuanya 1 gunakan kode `np.ones(shape, dtype)`.

In [5]:
array_all_zero = np.zeros((2,1), dtype=int)
print(array_all_zero)
print()
array_all_one = np.ones(5)
print(array_all_one)

[[0]
 [0]]

[1. 1. 1. 1. 1.]


## Membuat array dalam rentang angka

Kamu bisa membuat array dengan isi angka dalam rentang yang sudah ditentukan. batas bawah diikutkan tapi batas atas tidak.

In [6]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


## Membuat array dengan angka acak

NumPy menyediakan cara untuk membuat array dengan isian angka acak dalam selang angka yang telah ditentukan. Sebagai contoh `np.random.randint` menghasilkan nilai integer secara acak diantara batas bawah dan batas atas. Kode dibawah akan membuat vector 6-elemen berisi nilai integer acak diantara 50 sampai 100.

In [7]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[91 86 93 94 92 80]


Untuk membuat nilai float acak antara 0.0 sampai 1.0, gunakan kode `np.random.random`. Sebagai contoh

In [8]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.60526234 0.33833974 0.94749902 0.92594346 0.56698594 0.22758854]


## Operasi Matematika di NumPy operand

broadcasting , teknik yang digunakan NumPy untuk secara virtual memperbesar dimensi vector yang kecil supaya sesuai dengan dimensi vector yang besar supaya bisa dilakukan operasi linear aljabar. Contoh dibawah jika kita ingin menambahkan nilai 2 ke setiap item yang ada di vector.

In [9]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.60526234 2.33833974 2.94749902 2.92594346 2.56698594 2.22758854]


Kode dibawah contoh broadcasting perkalian

In [10]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[273 258 279 282 276 240]


## Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label` such that:

```
   label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
  label = (3)(6) + 4 = 22
 ```

In [11]:
feature = np.arange(6,21)
print(feature)
label = 3 * feature + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


contoh Jawaban dari Google


    #@title Double-click to see a possible solution to Task 1.
    feature = np.arange(6, 21)
    print(feature)
    label = (feature * 3) + 4
    print(label)


## Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the `label` array you already created. To be more precise, modify each value assigned to `label` by adding a *different* random floating-point value between -2 and +2. 

Don't rely on broadcasting. Instead, create a `noise` array having the same dimension as `label`.

In [12]:
noise = np.random.randint(low=-2, high=2, size=(15)) * np.random.random(15)
print(noise)
label = label + noise
print(label)

[ 0.         -0.02896337  0.          0.          0.         -0.74436208
  0.          0.46215911 -0.11184579  0.          0.         -0.36193176
 -1.18771311  0.03103528  0.        ]
[22.         24.97103663 28.         31.         34.         36.25563792
 40.         43.46215911 45.88815421 49.         52.         54.63806824
 56.81228689 61.03103528 64.        ]


Contoh jawaban dari Google

    #@title Double-click to see a possible solution to Task 2.

    noise = (np.random.random([15]) * 4) - 2
    print(noise)
    label = label + noise 
    print(label)